### ISSUE TITLE
Before upload hook

### ISSUE THREAD

**Issue by jimmiebtlr** [TheAncientGoat/autoform-slingshot#1]
It would be great to have a before upload hook to allow client side resize of image prior to upload.

Also, thanks a ton for putting together this package.

**Comment by ryanswrt** [comment]
Have a look at the commit I just pushed - You should be able to resize, in a synchronous way, the images; clone the package into your app's packages folder to test it.

**Comment by jimmiebtlr** [comment]
Thanks for the fast response.

It may be better to use callbacks instead of synchronous.
