### ISSUE TITLE
v1.0.0 release :: Issue #3 :: Deleting saved image does not update DB accordingly

### ISSUE THREAD

**Issue by kyooriouskoala** [TheAncientGoat/autoform-slingshot#12]
Removing an existing image and submitting the form to save it no longer update the DB accordingly as it would in the previous version.

**Comment by timbrandin** [comment]
How does the data look before and after saving the form?

**Comment by kyooriouskoala** [comment]
**Schema**

```
picture_url: {
    type: String,
    optional: true,
    autoform: {
        afFieldInput: {
            type: 'slingshotFileUpload',
            slingshotdirective: 'myFileUploads'
        }
    }
}
```

**DB**

```
{
    "_id" : "ZzFBkTncqsGZ2M4xS",
    "product" : "Cookie Monster",
    "createdBy" : "BjoP2iqpHgJyYmjv1",
    "createdAt" : ISODate("2015-07-29T04:55:25.178Z"),
    "editedBy" : "BjoP2iqpHgJyYmjv1",
    "editedAt" : ISODate("2015-08-03T10:10:24.914Z"),
    "picture_url" : "https://folhas.s3-ap-southeast-1.amazonaws.com/best/cookie.jpg"
}
```

No change to the `picture_url` key-value when removing the image and saving it. 

Replacing an existing image with a new one works fine.

**Comment by timbrandin** [comment]
Thx, I'll take a look at it. :)

**Comment by kyooriouskoala** [comment]
`timbrandin:autoform-slingshot@1.1.0`

**Test steps:**
1. Edit existing product entry.
2. Remove image.
3. Save.

**Result**
The `picture_url` key-value still exists in the collection doc.

**Comment by timbrandin** [comment]
Ok, I'll look into a little more. How about the other issues?

2015-08-04 12:05 GMT+02:00 kyooriouskoala notifications@github.com:

> timbrandin:autoform-slingshot@1.1.0
> 
> _Test steps:_
> 1. Edit existing product entry.
> 2. Remove image.
> 3. Save.
> 
> _Result_
> The picture_url key-value still exists in the collection doc.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TheAncientGoat/autoform-slingshot/issues/12#issuecomment-127553505
> .

## 

Cheers,
// Tim Brandin @timbrandin https://twitter.com/#!/timbrandin
http://timbrandin.com
http://studiointeract.com

**Comment by timbrandin** [comment]
This should be resolved in #13, would be great if you could confirm that @kyooriouskoala

**Comment by kyooriouskoala** [comment]
Hi @timbrandin, this issue is fixed! Thanks :)

**Comment by timbrandin** [comment]
Perfect!

Skickat från min iPhone
