### ISSUE TITLE
Few issues with regards to recent release v1.0.0

### ISSUE THREAD

**Issue by kyooriouskoala** [TheAncientGoat/autoform-slingshot#9]
Hi @TheAncientGoat and @timbrandin,

I notice a few issues!

<h3>:: Issue 1</h3>

I have a page that has two sections:

**Top section:** 
Form to add new product

**Bottom section:** 
Recently added products + (hidden) form

On the recently added product section, each of the product item in the list has an edit button and upon clicking it, the layout of that particular item will expand to show the form.

When editing the image upload field (removing existing image and choosing a new one), the blob image that appears on the "edit current product" form also appears on the "add new product" form which is not supposed to happen. 

<h3>:: Issue 2</h3>

Using the previous version (v0.0.2), the image would not appear if it did not get uploaded successfully and this in turn may appear as some sort of an indication for the user to notice that there is an issue with the image upload process. 

To provide a better user experience, it would be better to show the upload progress bar so that it is clear to the user that they will have to wait for the image upload to finish before they submit the form. That is the reason why I am asking for help to get the upload progress bar feature to work.

It is good that we now have a preview of the image (blob) before it gets uploaded but the way it works now, this function needs to be improved. 

Currently, if the user submits the form to save the changes while the image is not yet uploaded, the blob image path is saved to the DB. Because of that, there is just no clue at all for the user to notice that the image did not get saved properly since on the front end, the page will still show the image.

<h3>:: Issue 3</h3>

Removing an existing image and submitting the form to save it no longer update the DB accordingly as it would in the previous version.

If you need further clarification about the issues, please let me know. Thank you!

**Comment by timbrandin** [comment]
Can we separate this into separate issues? :) I'll have a look at it later today.

**Comment by kyooriouskoala** [comment]
Oh! OK, I'll do that now.
